[pytest]
testpaths = tests
pythonpath = .
addopts = -v -rfs --ignore=frontend --cov=backend --cov-fail-under 90 --cov-report term-missing -p no:warnings
python_files = tests.py test_*.py *_tests.py
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning