import * as monaco from "monaco-editor";
import apiIndex from "./playwrightApi.json";
import libIndex from "./libApi.json";

export const PYTHON_THEME = "vscode-dark-python";

// monaco 的 basic-languages 未被 treemended 编辑器打包, 这里内联 Python 语言配置。
const PYTHON_CONF: monaco.languages.LanguageConfiguration = {
  comments: { lineComment: "#", blockComment: ["", ""] },
  brackets: [
    ["{", "}"],
    ["[", "]"],
    ["(", ")"],
  ],
  autoClosingPairs: [
    { open: "{", close: "}" },
    { open: "[", close: "]" },
    { open: "(", close: ")" },
    { open: '"', close: '"', notIn: ["string"] },
    { open: "'", close: "'", notIn: ["string", "comment"] },
  ],
  surroundingPairs: [
    { open: "{", close: "}" },
    { open: "[", close: "]" },
    { open: "(", close: ")" },
    { open: '"', close: '"' },
    { open: "'", close: "'" },
  ],
  onEnterRules: [
    {
      beforeText: /^\s*(?:def|class|for|if|elif|else|while|try|with|finally|except|async|match|case)\b.*:\s*$/,
      action: { indentAction: monaco.languages.IndentAction.Indent },
    },
  ],
  folding: {
    markers: { start: /^\s*#region\b/, end: /^\s*#endregion\b/ },
  },
};

const knownClasses = new Set<string>();
for (const key of Object.keys((apiIndex as { classes: Record<string, unknown> }).classes)) {
  knownClasses.add(key.slice(key.lastIndexOf(".") + 1));
}
for (const key of Object.keys((libIndex as { classes: Record<string, unknown> }).classes)) {
  knownClasses.add(key.slice(key.lastIndexOf(".") + 1));
}

const knownModules = new Set<string>();
for (const key of Object.keys((libIndex as { modules: Record<string, unknown> }).modules)) {
  knownModules.add(key.split(".")[0]);
}

const language: monaco.languages.IMonarchLanguage = {
  defaultToken: "",
  tokenPostfix: ".python",
  keywords: [
    "False",
    "None",
    "True",
    "and",
    "as",
    "assert",
    "async",
    "await",
    "break",
    "case",
    "class",
    "continue",
    "def",
    "del",
    "elif",
    "else",
    "except",
    "finally",
    "for",
    "from",
    "global",
    "if",
    "import",
    "in",
    "is",
    "lambda",
    "match",
    "nonlocal",
    "not",
    "or",
    "pass",
    "raise",
    "return",
    "try",
    "while",
    "with",
    "yield",
  ],
  builtinTypes: [
    "basestring",
    "bool",
    "buffer",
    "bytearray",
    "bytes",
    "complex",
    "dict",
    "file",
    "float",
    "frozenset",
    "int",
    "list",
    "long",
    "memoryview",
    "object",
    "range",
    "set",
    "str",
    "tuple",
    "type",
    "unicode",
  ],
  builtinFunctions: [
    "__class__",
    "__dict__",
    "__import__",
    "__init__",
    "__name__",
    "abs",
    "all",
    "any",
    "apply",
    "bin",
    "callable",
    "chr",
    "classmethod",
    "cmp",
    "coerce",
    "compile",
    "delattr",
    "dir",
    "divmod",
    "enumerate",
    "eval",
    "exec",
    "execfile",
    "filter",
    "format",
    "getattr",
    "globals",
    "hasattr",
    "hash",
    "help",
    "hex",
    "id",
    "input",
    "intern",
    "isinstance",
    "issubclass",
    "iter",
    "len",
    "locals",
    "map",
    "max",
    "min",
    "next",
    "oct",
    "open",
    "ord",
    "pow",
    "print",
    "property",
    "range",
    "raw_input",
    "reduce",
    "reload",
    "repr",
    "reversed",
    "round",
    "setattr",
    "slice",
    "sorted",
    "staticmethod",
    "sum",
    "super",
    "unichr",
    "vars",
    "zip",
  ],
  brackets: [
    { open: "{", close: "}", token: "delimiter.curly" },
    { open: "[", close: "]", token: "delimiter.bracket" },
    { open: "(", close: ")", token: "delimiter.parenthesis" },
  ],
  knownClasses: Array.from(knownClasses),
  knownModules: Array.from(knownModules),
  tokenizer: {
    root: [
      { include: "@whitespace" },
      { include: "@numbers" },
      { include: "@strings" },
      [/\b(class)(\s+)([a-zA-Z_]\w*)/, ["keyword", "white", "entity.name.type"]],
      [/\b(def)(\s+)([a-zA-Z_]\w*)/, ["keyword", "white", "entity.name.function"]],
      [/\b(import|from)\b/, "keyword", "@imports"],
      [/[,:;]/, "delimiter"],
      [/[{}\[\]()]/, "@brackets"],
      [/[+\-*/%=<>!&|^~]+/, "operator"],
      [/@[a-zA-Z_]\w*/, "decorator"],
      [
        /[A-Z_][A-Z0-9_]*\b/,
        {
          cases: {
            "@keywords": "keyword",
            "@knownModules": "support.type",
            "@builtinTypes": "support.type",
            "@knownClasses": "support.type",
            "@default": "constant",
          },
        },
      ],
      [
        /[a-zA-Z_]\w*(?=\()/,
        {
          cases: {
            "@keywords": "keyword",
            "@knownModules": "support.type",
            "@builtinTypes": "support.type",
            "@knownClasses": "support.type",
            "@builtinFunctions": "support.function",
            "@default": "entity.name.function",
          },
        },
      ],
      [
        /[a-zA-Z_]\w*/,
        {
          cases: {
            "@keywords": "keyword",
            "@knownModules": "support.type",
            "@builtinTypes": "support.type",
            "@knownClasses": "support.type",
            "@builtinFunctions": "support.function",
            "@default": "identifier",
          },
        },
      ],
    ],
    imports: [
      [/\s+/, { cases: { "@eos": { token: "white", next: "@pop" }, "@default": "white" } }],
      [/#.*$/, "comment", "@pop"],
      [/\b(import|from|as)\b/, "keyword"],
      [/[,]/, "delimiter"],
      [/[()]/, { cases: { "@eos": { token: "@brackets", next: "@pop" }, "@default": "@brackets" } }],
      [/[.]/, "operator"],
      [/[*]/, "operator"],
      [
        /[a-zA-Z_]\w*/,
        {
          cases: {
            "@eos": { token: "support.type", next: "@pop" },
            "@default": "support.type",
          },
        },
      ],
      [/./, "default", "@pop"],
    ],
    whitespace: [
      [/\s+/, "white"],
      [/(^#.*$)/, "comment"],
      [/'''/, "string", "@endDocString"],
      [/"""/, "string", "@endDblDocString"],
    ],
    endDocString: [
      [/[^']+/, "string"],
      [/\\'/, "string"],
      [/'''/, "string", "@popall"],
      [/'/, "string"],
    ],
    endDblDocString: [
      [/[^"]+/, "string"],
      [/\\"/, "string"],
      [/"""/, "string", "@popall"],
      [/"/, "string"],
    ],
    numbers: [
      [/-?0x([abcdef]|[ABCDEF]|\d)+[lL]?/, "number.hex"],
      [/-?(\d*\.)?\d+([eE][+\-]?\d+)?[jJ]?[lL]?/, "number"],
    ],
    strings: [
      [/'$/, "string.escape", "@popall"],
      [/f'{1,3}/, "string.escape", "@fStringBody"],
      [/'/, "string.escape", "@stringBody"],
      [/"$/, "string.escape", "@popall"],
      [/f"{1,3}/, "string.escape", "@fDblStringBody"],
      [/"/, "string.escape", "@dblStringBody"],
    ],
    fStringBody: [
      [/[^\\'\{\}]+$/, "string", "@popall"],
      [/[^\\'\{\}]+/, "string"],
      [/\{[^\}':!=]+/, "identifier", "@fStringDetail"],
      [/\\./, "string"],
      [/'/, "string.escape", "@popall"],
      [/\\$/, "string"],
    ],
    stringBody: [
      [/[^\\']+$/, "string", "@popall"],
      [/[^\\']+/, "string"],
      [/\\./, "string"],
      [/'/, "string.escape", "@popall"],
      [/\\$/, "string"],
    ],
    fDblStringBody: [
      [/[^\\"\{\}]+$/, "string", "@popall"],
      [/[^\\"\{\}]+/, "string"],
      [/\{[^\}':!=]+/, "identifier", "@fStringDetail"],
      [/\\./, "string"],
      [/"/, "string.escape", "@popall"],
      [/\\$/, "string"],
    ],
    dblStringBody: [
      [/[^\\"]+$/, "string", "@popall"],
      [/[^\\"]+/, "string"],
      [/\\./, "string"],
      [/"/, "string.escape", "@popall"],
      [/\\$/, "string"],
    ],
    fStringDetail: [
      [/[:][^}]+/, "string"],
      [/[!][ars]/, "string"],
      [/=/, "string"],
      [/\}/, "identifier", "@pop"],
    ],
  },
};

export function registerPythonTheme() {
  monaco.languages.register({ id: "python", extensions: [".py", ".pyi"], aliases: ["Python", "python"] });
  monaco.languages.setLanguageConfiguration("python", PYTHON_CONF);
  monaco.languages.setMonarchTokensProvider("python", language);
  monaco.editor.defineTheme(PYTHON_THEME, {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "D4D4D4", background: "1E1E1E" },
      { token: "keyword", foreground: "C586C0" },
      { token: "constant", foreground: "569CD6" },
      { token: "identifier", foreground: "9CDCFE" },
      { token: "variable", foreground: "9CDCFE" },
      { token: "parameter", foreground: "9CDCFE" },
      { token: "entity.name.function", foreground: "DCDCAA" },
      { token: "support.function", foreground: "DCDCAA" },
      { token: "entity.name.type", foreground: "4EC9B0" },
      { token: "support.type", foreground: "4EC9B0" },
      { token: "decorator", foreground: "DCDCAA" },
      { token: "string", foreground: "CE9178" },
      { token: "string.escape", foreground: "D7BA7D" },
      { token: "number", foreground: "B5CEA8" },
      { token: "number.hex", foreground: "B5CEA8" },
      { token: "comment", foreground: "6A9955" },
      { token: "delimiter", foreground: "D4D4D4" },
      { token: "operator", foreground: "D4D4D4" },
      { token: "white", foreground: "D4D4D4" },
    ],
    colors: {
      "editor.background": "#1E1E1E",
      "editor.foreground": "#D4D4D4",
      "editorInlayHint.foreground": "#9DA5B0",
      "editorInlayHint.background": "#262626",
      "editorInlayHint.parameterForeground": "#9DA5B0",
      "editorInlayHint.parameterBackground": "#262626",
    },
  });
}
